### PR TITLE
Lesson 1

### PR DESCRIPTION
**Pull request by dmwelch**

### CODE REVIEW

**Comment by bucktower** [comment]
Hey dmwelch, I'm sorry I've been pretty inactive as of lately. I'm gonna add these right in!

**Comment by bucktower** [comment]
Would you like collaborator access on this repo and Zeuscraft? Since I'm not in active dev of either anymore, I figured  I could just transfer ownership to you.

**Comment by dmwelch** [comment]
I'm rewriting the TutorialMod as a primer for our local CoderDojo, so I'm still learning.  In any case, I don't have enough free time to maintain Zeuscraft.   

Once our ninjas have modding down, I could always ask if anyone is interested in being a collaborator?

**Comment by bucktower** [comment]
Sure!

**Pull request merged**
